title: Minimal theme	
description: Minimal is a theme for GitHub Pages.	
theme: jekyll-theme-dinky
github:
  zip_url: http://example.com/download.zip
  another_url: another value
  lab1_url: another value
  lab2_url: another value
  lab3_url: another value
  home_url: another value
